# Generated by Django 5.1.1 on 2024-12-05 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True)),
                ("am8", models.IntegerField(blank=True)),
                ("am9", models.IntegerField(blank=True)),
                ("am10", models.IntegerField(blank=True)),
                ("am11", models.IntegerField(blank=True)),
                ("am12", models.IntegerField(blank=True)),
                ("pm1", models.IntegerField(blank=True)),
                ("pm2", models.IntegerField(blank=True)),
                ("pm3", models.IntegerField(blank=True)),
                ("pm4", models.IntegerField(blank=True)),
                ("pm5", models.IntegerField(blank=True)),
                ("pm6", models.IntegerField(blank=True)),
                ("pm7", models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="TechnicianProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("alt_phone", models.CharField(blank=True, max_length=15)),
                ("gender", models.CharField(blank=True, max_length=15)),
                (
                    "lattitude",
                    models.DecimalField(
                        blank=True, decimal_places=11, max_digits=15, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=11, max_digits=15, null=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=20)),
                ("isworking", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to="Technician_images/",
                    ),
                ),
                ("deviceid", models.CharField(blank=True, max_length=200)),
                (
                    "userObj",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechniciansEarnings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("earnings", models.IntegerField(default=0)),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Technicians.technicianprofile",
                    ),
                ),
            ],
        ),
    ]
