# Generated by Django 5.1.1 on 2024-12-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Technicians", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technicianprofile",
            name="deviceid",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
