# Generated by Django 5.1.1 on 2024-12-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productsmaincategories",
            old_name="managedby",
            new_name="managedbyadmin",
        ),
    ]
